name = "cf-telegram-worker"
main = "cloudflare-worker.js"
compatibility_date = "2025-07-30"

# TELEGRAM_BOT_TOKEN = "your_bot_token_here"
# TELEGRAM_CHAT_ID = "your_chat_id_here"

[vars]

[observability.logs]
enabled = true