[env.production]
name = "cf-telegram-worker"
main = "cloudflare-worker.js"
compatibility_date = "2025-07-30"

# Environment variables (these will need to be set in Cloudflare dashboard or via wrangler secrets)
# TELEGRAM_BOT_TOKEN = "your_bot_token_here"
# TELEGRAM_CHAT_ID = "your_chat_id_here"

[env.production.vars]
# Add any non-secret environment variables here if needed
